


```{r setup}
knitr::opts_knit$set(root.dir ='/Users/najah/work/internships/meghna/LT05_L1TP_145044_20100428_20161016_01_T1/')

library(tidyverse)
```


```{r}

random_points = read.csv("./145044_20100428_indices/random_points_indices_data.csv")
head(random_points)

```



```{r}
# melting the df for viz
indices_df = random_points[,c('class_label','ndvi', 'ndmi', 'nbr', 'bai', 'baims', 'baiml', 'mirbi', 'gemi')] %>% 
  pivot_longer(cols = -class_label, names_to = "indices") %>% 
  filter(class_label != 'No Data')

head(indices_df)

indices_avg = indices_df %>% group_by(class_label, indices) %>% 
  summarise(mean = mean(value, na.rm = TRUE)) %>%  ungroup()


indices_df
```
## setting theme for the boxplot

```{r}
theme_bp =   theme_bw() +
  theme(plot.margin = unit(c(.5,.5,.5,.5), "cm"),
        plot.title = element_text( size = 18, family = "serif", hjust = .5),
        plot.subtitle = element_text( size = 15,color = "grey50",
                                     margin = margin(t = 0, r = 0, b = 20, l = 0)),
        text = element_text(color = "gray20",family = "serif"),
      
        #axis.text = element_text(face = "italic", size = 10),
            
        axis.ticks = element_blank(),
    
        #axis.title.x = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
       # axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
        axis.line.y = element_line(),
        axis.title.y = element_blank()
  )  
```


```{r}


  
df_sub = indices_df[-which(indices_df$class_label=='Water' & indices_df$indices %in% c('bai', 'baiml', 'baims')),]



df_sub$indices = factor(df_sub$indices, levels = c('ndvi','gemi','bai', 'baims', 'nbr', 'mirbi', 'baiml', 'ndmi'), labels =c('NDVI','GEMI', 'BAI', 'BAIMS', 'NBR', 'MIRBI', 'BAIML', 'NDMI') )

si_1 =ggplot(df_sub, aes(y= class_label, x= value))+
  geom_boxplot()+
  facet_wrap(~indices, scales = 'free_x', nrow =4)+
  theme_bp

ggsave("~/work/internships/meghna/fire_images/si_boxplot.tiff",
       device='tiff',
       plot = si_1,
        width = 6, height = 12,
       dpi = 300)
```





















