

## Indices vizes

loading wajida's indices

```{r}
library(raster)
"rgdal_show_exportToProj4_warnings"="none"
library(rgdal)
library(ggplot2)
library(stars)

```

```{r}
## theme 
theme_set(theme_bw())

theme_for_map <- theme(
  axis.ticks = element_blank(),
  axis.text= element_blank(), 
  axis.line = element_blank(),
  panel.border = element_blank(),
  panel.grid.major = element_line(color='transparent'),
  panel.grid.minor = element_line(color='transparent'),
  panel.background = element_blank(),
  plot.background = element_rect(fill = "transparent",color='transparent'),
  legend.title = element_blank(),
  axis.title = element_blank(),
  plot.title = element_text(hjust = .55, vjust = -5, family = 'serif'),
  legend.position = c(.965,.18),
  legend.key.size = unit(.5, 'cm'), #change legend key size
  legend.key.height = unit(.5, 'cm'), #change legend key height
  legend.key.width = unit(.5, 'cm'), #change legend key width
  legend.text = element_text(size=5) #change legend text font size
)
```


## NDVI
```{r}

ndvi_path = '~/work/internships/meghna/wajida_files/indices/NDVI_WS.tif'
ndvi_raster <- read_stars(ndvi_path)
# plot(ndvi_raster)
```


```{r}

## ndvi plotting

breaks = unname(quantile(ndvi_raster[["NDVI_WS.tif"]],  na.rm = TRUE, probs = seq(0, 1,.1)))

#breaks = append(breaks, c(.01), after = 1) 

library(scales)

ndvi <- ggplot()+
  geom_stars(data = ndvi_raster, downsample = 2)+
  scale_x_continuous(expand = c(0, 0)) + 
  scale_y_continuous(expand = c(0, 0))+

 scale_fill_fermenter(palette = "Spectral", breaks = round(breaks,2),direction = 1,
                      na.value=NA)+
  theme_for_map +
  labs(title = 'NDVI')

ggsave("~/work/internships/meghna/wajida_files/images/ndvi.tif",
       device='tiff',
       plot = ndvi,
        width = 4.5, height = 4,
       dpi = 300,
       bg='#ffffff')

```


## NBR

```{r}

nbr_path = '~/work/internships/meghna/wajida_files/indices/NBR_WS.tif'
nbr_raster<- read_stars(nbr_path)
plot(nbr_raster)
```

```{r}

## nbr plotting


breaks = unname(quantile(nbr_raster[["NBR_WS.tif"]],  na.rm = TRUE, probs = seq(0, 1,.1)))

#breaks = append(breaks, c(.200000), after = 10)
nbr <- ggplot()+
  geom_stars(data = nbr_raster, downsample = 2)+
  scale_fill_fermenter( palette = "Spectral",breaks = round(breaks,2) , na.value=NA , direction = 1)+
  scale_x_continuous(expand = c(0, 0)) + 
  scale_y_continuous(expand = c(0, 0))+
  labs(title = 'NBR')+
  theme_for_map 
    
# 
ggsave("~/work/internships/meghna/wajida_files/images/nbr.tif",
        device='tiff',
        plot = nbr,
        width = 4.5, height = 4,
       dpi = 300,
       bg='#ffffff')
```

## GEMI


```{r}

gemi_path = '~/work/internships/meghna/wajida_files/indices/GEMI.tif'
gemi_raster<- read_stars(gemi_path)
plot(gemi_raster)

```

```{r}
## gemi plotting



breaks = unname(quantile(gemi_raster[["GEMI.tif"]],  na.rm = TRUE, probs = seq(0, 1,.1)))
#breaks = breaks[1:9]
#breaks = append(breaks, c(0.3131032), after = 0.3331032)
  
gemi <- ggplot()+
  geom_stars(data = gemi_raster, downsample = 2)+
    scale_fill_fermenter(breaks = round(breaks,2), palette = 'Spectral', direction =1, na.value =NA)+
    theme_for_map+
  scale_x_continuous(expand = c(0, 0)) + 
  scale_y_continuous(expand = c(0, 0))+
  labs(title = 'GEMI')

ggsave("~/work/internships/meghna/wajida_files/images/GEMI.tif",
        device='tiff',
        plot = gemi,
        width = 4.5, height = 4,
       dpi = 300,
       bg='#ffffff')
```

#### bai

```{r}

bai_path = '~/work/internships/meghna/wajida_files/indices/BAI.tif'
bai_raster<- read_stars(bai_path)
plot(bai_raster)

```

```{r}
breaks = unname(quantile(bai_raster[["BAI.tif"]],  na.rm = TRUE, probs = seq(0, 1,.1)))

#breaks = append(breaks, c(500), abaifter =10)
bai <- ggplot()+
  geom_stars(data = bai_raster, downsample = 2)+
   scale_fill_fermenter(breaks = round(breaks), palette = "Spectral", na.value = NA)+
  theme_for_map +
  scale_x_continuous(expand = c(0, 0)) + 
  scale_y_continuous(expand = c(0, 0))+
  labs(title = "BAI")


ggsave("~/work/internships/meghna/wajida_files/images/bai.tif",
       plot = bai,
        device='tiff',
        width = 4.5, height = 4,
       dpi = 300,
       bg='#ffffff')
```

#### baiml

```{r}

baiml_path = '~/work/internships/meghna/wajida_files/indices/BAIML.tif'
baiml_raster<- read_stars(baiml_path)
plot(baiml_raster)

```

```{r}
breaks = unname(quantile(baiml_raster[["BAIML.tif"]],  na.rm = TRUE, probs = seq(0, 1,.1)))

#breaks = append(breaks, c(500), after = 1.220539e+06)
baiml <- ggplot()+
  geom_stars(data = baiml_raster, downsample = 2)+
   scale_fill_fermenter(breaks = round(breaks), palette = "Spectral", na.value = NA)+
  theme_for_map +
  scale_x_continuous(expand = c(0, 0)) + 
  scale_y_continuous(expand = c(0, 0))+
  labs(title = "BAIML")

ggsave("~/work/internships/meghna/wajida_files/images/baiml.tif",
       plot = baiml,
             device='tiff',
        width = 4.5, height = 4,
       dpi = 300,
       bg='#ffffff')
```

#### baims

```{r}

baims_path = '~/work/internships/meghna/wajida_files/indices/BAIMS.tif'
baims_raster<- read_stars(baims_path)
plot(baims_raster)

```

```{r}
breaks = unname(quantile(baims_raster[["BAIMS.tif"]],  na.rm = TRUE, probs = seq(0, 1,.1)))

#breaks[10] <- 50

#breaks = append(breaks, c(500), after = 1.220539e+06)
baims <- ggplot()+
  geom_stars(data = baims_raster, downsample = 2)+
   scale_fill_fermenter(breaks = round(breaks), palette = "Spectral", na.value = NA)+
  theme_for_map +
  scale_x_continuous(expand = c(0, 0)) + 
  scale_y_continuous(expand = c(0, 0))+
  labs(title = 'BAIMS')

ggsave("~/work/internships/meghna/wajida_files/images/baims.tif",
       plot = baims,
        device='tiff',
        width = 4.5, height = 4,
       dpi = 300,
       bg='#ffffff')
```

#### ndmi

```{r}
ndmi_raster<- read_stars('~/work/internships/meghna/wajida_files/indices/NDMI.tif')
plot(ndmi_raster)

```

```{r}
breaks = unname(quantile(ndmi_raster[["NDMI.tif"]],  na.rm = TRUE, probs = seq(0, 1,.1)))
#breaks = c(-.6, 0, .1,.2, .4, .6, .8,1)

#breaks[10] <- 50

#breaks = append(breaks, c(500), after = 1.220539e+06)
ndmi <- ggplot()+
  geom_stars(data = ndmi_raster, downsample = 2)+
   scale_fill_fermenter(breaks = round(breaks,2), palette = "Spectral", na.value = NA, direction = 1)+
  theme_for_map +
  scale_x_continuous(expand = c(0, 0)) + 
  scale_y_continuous(expand = c(0, 0))+
  labs(title = 'NDMI')

ggsave("~/work/internships/meghna/wajida_files/images/ndmi.tif",
       plot = ndmi,
        device='tiff',
        width = 4.5, height = 4,
       dpi = 300,
       bg='#ffffff')
```

#### mirbi

```{r}
mirbi_raster<- read_stars('~/work/internships/meghna/wajida_files/indices/MIRBI.tif')
plot(mirbi_raster)

```

```{r}
breaks = unname(quantile(mirbi_raster[["MIRBI.tif"]],  na.rm = TRUE, probs = seq(0, 1,.1)))
#breaks = c(-.6, 0, .1,.2, .4, .6, .8,1)

#breaks[10] <- 50

#breaks = append(breaks, c(4), after = 10)
mirbi <- ggplot()+
  geom_stars(data = mirbi_raster, downsample = 2)+
   scale_fill_fermenter(breaks = round(breaks,2), palette = "Spectral", na.value = NA, direction = -1)+
  theme_for_map +
  scale_x_continuous(expand = c(0, 0)) + 
  scale_y_continuous(expand = c(0, 0))+
  labs(title = 'MIRBI')

ggsave("~/work/internships/meghna/wajida_files/images/mirbi.tif",
       plot = mirbi,
        device='tiff',
        width = 4.5, height = 4,
       dpi = 300,
       bg='#ffffff')
```
